package acs.utils;

public enum ExternalServiceType {
    GENERAL,
    SHOPPING_CATALOG_SERVICE,
    PRODUCT_RETURN_AND_REFUND,
    TRACKING_SERVICE,
    BLOG_COMMENTS_SERVICE,
    SHOPPING_CART_SERVICE
}
